# Generated by Django 4.1.2 on 2023-02-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_timestamp', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('order_desc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_name', models.CharField(blank=True, max_length=255, null=True)),
                ('packaging_descr', models.CharField(blank=True, max_length=1000, null=True)),
                ('packaging_store', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Packaging',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_descr', models.CharField(blank=True, max_length=1000, null=True)),
                ('quant', models.IntegerField(blank=True, db_column='quant', null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=100, null=True)),
                ('price_all', models.FloatField()),
                ('price_per_piece', models.FloatField()),
                ('article', models.IntegerField(blank=True, db_column='article', null=True)),
                ('packaging', models.ForeignKey(blank=True, db_column='packaging_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.packaging')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(blank=True, db_column='quant', null=True)),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.order')),
                ('packaging', models.ForeignKey(blank=True, db_column='packaging', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.packaging')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.product')),
            ],
            options={
                'db_table': 'OrderProduct',
                'managed': True,
            },
        ),
    ]
